### ISSUE TITLE
Basic VR Movement System

### ISSUE THREAD

**Issue by MagicalBean** [theketchupdude/OGPC-Project#2]
I'm not sure but I figured this would be the best/easiest place to talk about Tom's new fix. So, you did it, the camera is in the right place and the movement works correctly, obviously needs movement/turning speeds and such adjusted but that's easy. Also the collision is a little weird, the blocks start clipping when you get into them. Last of all I don't think you tried to fix it but the bananas still need to be fixed, they still are at a weird offset from the actual controllers. But hurrah the camera is now working!

**Comment by theketchupdude** [comment]
Hmm... Seems like the vr headset doesn't care about collisions.
As for the bananas, they are probably supposed to auto center. Just need to move them to the origin.

**Comment by MagicalBean** [comment]
Alright cool seems simple enough, I think the collision works since it’s on
the object so it collided the near clipping plane just needs to be adjusted
I think.

**Comment by MagicalBean** [comment]
Do you think you can fix the Bananas before you leave for Colorado Tom, if not at least try to tell me what I need to fix, if you don't have time for either it's ok and we can work on it in the future.

**Comment by theketchupdude** [comment]
Bananas should be fixed.
