### ISSUE TITLE
Will this work?

### ISSUE THREAD

**Issue by theketchupdude** [theketchupdude/OGPC-Project#5]
![Enemy movement](https://user-images.githubusercontent.com/38171793/55449437-5c0c5e00-5580-11e9-94a1-0c1b9e0da8d7.PNG)

**Comment by MagicalBean** [comment]
Okay, I have figured out the problem, and it is with your custom Nav Mesh Agent. You didn't create the test agent correctly in the navigation window. I can either make it, or we can just adjust the humanoid one to be the same thing. I don't see any reason not to just adjust the humanoid but if you disagree, please tell me.

**Comment by theketchupdude** [comment]
Okay, you can change it to the Humanoid agent.

**Comment by MagicalBean** [comment]
Alright, sounds good.
